version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    links:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
  db:
    image: postgres:9.6
